<?php

//$_POST["model"];
//$_POST["round"];

$model = $_SESSION["round"];
$round = $_SESSION["model"];

$filename = '../start';
$fp = fopen("".$filename, 'wb');
if (!$fp)
{
    echo '<p><strong>Cannot generate message file</strong></p></body></html>';
    exit;
} 
else
{
	$outputstring  = 'Hello, i have been generated by the button';
	save_setup($model, $round);
	fwrite($fp, $outputstring);
}

function save_setup($select_model, $round_number){
	$filename = "../data/round_setup/round.xml";
	$fp = fopen("".$filename, 'wb');

	$outputstring = "<round_info>
		<level>$round_number</level>
		<start_time>" . time() . "</start_time>
		<setup>
			<graph>" . strtoupper($select_model) . "</graph>
			<constants>
			" . get_constants() . "
			</constants>
		</setup>
	</round_info>";
	
	fwrite($fp, $outputstring);
 }
 
function get_constants(){	
	$contants = fopen("../constants.xml","r");

	$content = "";

	while(! feof($contants))
	  {
		$content .= fgets($contants);
	  }

	fclose($contants);
	
	return $content;
}

?>